/** O*NET-style alias pairs (961 entries) */
export const ONET_ALIAS_PAIRS: ReadonlyArray<readonly [string, string]> = [
  ["javascript", "JavaScript"],
  ["js", "JavaScript"],
  ["javascript", "JavaScript"],
  ["ecmascript", "JavaScript"],
  ["es6", "JavaScript"],
  ["es2015", "JavaScript"],
  ["vanilla js", "JavaScript"],
  ["typescript", "TypeScript"],
  ["ts", "TypeScript"],
  ["typescript", "TypeScript"],
  ["typed javascript", "TypeScript"],
  ["python", "Python"],
  ["py", "Python"],
  ["python", "Python"],
  ["python3", "Python"],
  ["python 3", "Python"],
  ["java", "Java"],
  ["java", "Java"],
  ["jdk", "Java"],
  ["jvm", "Java"],
  ["c++", "C++"],
  ["c++", "C++"],
  ["cpp", "C++"],
  ["cplusplus", "C++"],
  ["c#", "C#"],
  ["c#", "C#"],
  ["csharp", "C#"],
  ["dotnet", "C#"],
  [".net", "C#"],
  ["go", "Go"],
  ["go", "Go"],
  ["golang", "Go"],
  ["rust", "Rust"],
  ["rust", "Rust"],
  ["rustlang", "Rust"],
  ["ruby", "Ruby"],
  ["ruby", "Ruby"],
  ["rails", "Ruby"],
  ["ruby on rails", "Ruby"],
  ["php", "PHP"],
  ["php", "PHP"],
  ["laravel", "PHP"],
  ["swift", "Swift"],
  ["swift", "Swift"],
  ["swiftui", "Swift"],
  ["kotlin", "Kotlin"],
  ["kotlin", "Kotlin"],
  ["scala", "Scala"],
  ["scala", "Scala"],
  ["akka", "Scala"],
  ["r", "R"],
  ["r", "R"],
  ["r language", "R"],
  ["sql", "SQL"],
  ["sql", "SQL"],
  ["t-sql", "SQL"],
  ["plsql", "SQL"],
  ["postgresql", "PostgreSQL"],
  ["postgres", "PostgreSQL"],
  ["postgresql", "PostgreSQL"],
  ["pg", "PostgreSQL"],
  ["psql", "PostgreSQL"],
  ["mysql", "MySQL"],
  ["mysql", "MySQL"],
  ["mariadb", "MySQL"],
  ["mongodb", "MongoDB"],
  ["mongo", "MongoDB"],
  ["mongodb", "MongoDB"],
  ["redis", "Redis"],
  ["redis", "Redis"],
  ["react", "React"],
  ["react", "React"],
  ["react.js", "React"],
  ["reactjs", "React"],
  ["angular", "Angular"],
  ["angular", "Angular"],
  ["angularjs", "Angular"],
  ["vue.js", "Vue.js"],
  ["vue", "Vue.js"],
  ["vuejs", "Vue.js"],
  ["vue.js", "Vue.js"],
  ["next.js", "Next.js"],
  ["next", "Next.js"],
  ["nextjs", "Next.js"],
  ["next.js", "Next.js"],
  ["node.js", "Node.js"],
  ["node", "Node.js"],
  ["nodejs", "Node.js"],
  ["node.js", "Node.js"],
  ["express", "Express"],
  ["express", "Express"],
  ["expressjs", "Express"],
  ["django", "Django"],
  ["django", "Django"],
  ["flask", "Flask"],
  ["flask", "Flask"],
  ["fastapi", "FastAPI"],
  ["fastapi", "FastAPI"],
  ["spring", "Spring"],
  ["spring", "Spring"],
  ["spring boot", "Spring"],
  ["springboot", "Spring"],
  ["graphql", "GraphQL"],
  ["graphql", "GraphQL"],
  ["apollo graphql", "GraphQL"],
  ["rest api", "REST API"],
  ["rest", "REST API"],
  ["restful", "REST API"],
  ["rest api", "REST API"],
  ["html", "HTML"],
  ["html", "HTML"],
  ["html5", "HTML"],
  ["css", "CSS"],
  ["css", "CSS"],
  ["css3", "CSS"],
  ["sass", "Sass"],
  ["sass", "Sass"],
  ["scss", "Sass"],
  ["tailwind css", "Tailwind CSS"],
  ["tailwind", "Tailwind CSS"],
  ["tailwind css", "Tailwind CSS"],
  ["tailwindcss", "Tailwind CSS"],
  ["docker", "Docker"],
  ["docker", "Docker"],
  ["containerization", "Docker"],
  ["kubernetes", "Kubernetes"],
  ["kubernetes", "Kubernetes"],
  ["k8s", "Kubernetes"],
  ["kube", "Kubernetes"],
  ["terraform", "Terraform"],
  ["terraform", "Terraform"],
  ["tf", "Terraform"],
  ["aws", "AWS"],
  ["aws", "AWS"],
  ["amazon web services", "AWS"],
  ["ec2", "AWS"],
  ["s3", "AWS"],
  ["lambda", "AWS"],
  ["microsoft azure", "Microsoft Azure"],
  ["azure", "Microsoft Azure"],
  ["microsoft azure", "Microsoft Azure"],
  ["google cloud platform", "Google Cloud Platform"],
  ["gcp", "Google Cloud Platform"],
  ["google cloud", "Google Cloud Platform"],
  ["ci/cd", "CI/CD"],
  ["ci/cd", "CI/CD"],
  ["cicd", "CI/CD"],
  ["continuous integration", "CI/CD"],
  ["jenkins", "Jenkins"],
  ["jenkins", "Jenkins"],
  ["github actions", "GitHub Actions"],
  ["github actions", "GitHub Actions"],
  ["git", "Git"],
  ["git", "Git"],
  ["github", "Git"],
  ["gitlab", "Git"],
  ["linux", "Linux"],
  ["linux", "Linux"],
  ["unix", "Linux"],
  ["ubuntu", "Linux"],
  ["agile", "Agile"],
  ["agile", "Agile"],
  ["scrum", "Agile"],
  ["kanban", "Agile"],
  ["machine learning", "Machine Learning"],
  ["ml", "Machine Learning"],
  ["machine learning", "Machine Learning"],
  ["deep learning", "Deep Learning"],
  ["deep learning", "Deep Learning"],
  ["neural networks", "Deep Learning"],
  ["tensorflow", "TensorFlow"],
  ["tensorflow", "TensorFlow"],
  ["pytorch", "PyTorch"],
  ["pytorch", "PyTorch"],
  ["natural language processing", "Natural Language Processing"],
  ["nlp", "Natural Language Processing"],
  ["natural language processing", "Natural Language Processing"],
  ["computer vision", "Computer Vision"],
  ["computer vision", "Computer Vision"],
  ["cv", "Computer Vision"],
  ["data analysis", "Data Analysis"],
  ["data analysis", "Data Analysis"],
  ["analytics", "Data Analysis"],
  ["data engineering", "Data Engineering"],
  ["data engineering", "Data Engineering"],
  ["etl", "Data Engineering"],
  ["apache spark", "Apache Spark"],
  ["spark", "Apache Spark"],
  ["apache spark", "Apache Spark"],
  ["pyspark", "Apache Spark"],
  ["hadoop", "Hadoop"],
  ["hadoop", "Hadoop"],
  ["hdfs", "Hadoop"],
  ["kafka", "Kafka"],
  ["kafka", "Kafka"],
  ["apache kafka", "Kafka"],
  ["tableau", "Tableau"],
  ["tableau", "Tableau"],
  ["power bi", "Power BI"],
  ["power bi", "Power BI"],
  ["powerbi", "Power BI"],
  ["excel", "Excel"],
  ["excel", "Excel"],
  ["spreadsheets", "Excel"],
  ["financial modeling", "Financial Modeling"],
  ["financial modeling", "Financial Modeling"],
  ["dcf model", "Financial Modeling"],
  ["bloomberg", "Bloomberg"],
  ["bloomberg", "Bloomberg"],
  ["accounting", "Accounting"],
  ["accounting", "Accounting"],
  ["gaap", "Accounting"],
  ["risk management", "Risk Management"],
  ["risk management", "Risk Management"],
  ["credit risk", "Risk Management"],
  ["compliance", "Compliance"],
  ["compliance", "Compliance"],
  ["regulatory compliance", "Compliance"],
  ["hipaa", "HIPAA"],
  ["hipaa", "HIPAA"],
  ["clinical research", "Clinical Research"],
  ["clinical research", "Clinical Research"],
  ["clinical trials", "Clinical Research"],
  ["patient care", "Patient Care"],
  ["patient care", "Patient Care"],
  ["electronic health records", "Electronic Health Records"],
  ["ehr", "Electronic Health Records"],
  ["emr", "Electronic Health Records"],
  ["salesforce", "Salesforce"],
  ["salesforce", "Salesforce"],
  ["sfdc", "Salesforce"],
  ["crm", "CRM"],
  ["crm", "CRM"],
  ["lead generation", "Lead Generation"],
  ["lead generation", "Lead Generation"],
  ["prospecting", "Lead Generation"],
  ["negotiation", "Negotiation"],
  ["negotiation", "Negotiation"],
  ["deal closing", "Negotiation"],
  ["account management", "Account Management"],
  ["account management", "Account Management"],
  ["adobe creative suite", "Adobe Creative Suite"],
  ["adobe", "Adobe Creative Suite"],
  ["photoshop", "Adobe Creative Suite"],
  ["illustrator", "Adobe Creative Suite"],
  ["figma", "Figma"],
  ["figma", "Figma"],
  ["ux design", "UX Design"],
  ["ux", "UX Design"],
  ["ux design", "UX Design"],
  ["ui design", "UI Design"],
  ["ui", "UI Design"],
  ["ui design", "UI Design"],
  ["content strategy", "Content Strategy"],
  ["content strategy", "Content Strategy"],
  ["contract law", "Contract Law"],
  ["contract law", "Contract Law"],
  ["contracts", "Contract Law"],
  ["litigation", "Litigation"],
  ["litigation", "Litigation"],
  ["legal research", "Legal Research"],
  ["legal research", "Legal Research"],
  ["westlaw", "Legal Research"],
  ["project management", "Project Management"],
  ["project management", "Project Management"],
  ["pmp", "Project Management"],
  ["product management", "Product Management"],
  ["product management", "Product Management"],
  ["communication", "Communication"],
  ["communication", "Communication"],
  ["leadership", "Leadership"],
  ["leadership", "Leadership"],
  ["team leadership", "Leadership"],
  ["problem solving", "Problem Solving"],
  ["problem solving", "Problem Solving"],
  ["jira", "Jira"],
  ["jira", "Jira"],
  ["confluence", "Confluence"],
  ["confluence", "Confluence"],
  ["splunk", "Splunk"],
  ["splunk", "Splunk"],
  ["datadog", "Datadog"],
  ["datadog", "Datadog"],
  ["prometheus", "Prometheus"],
  ["prometheus", "Prometheus"],
  ["grafana", "Grafana"],
  ["grafana", "Grafana"],
  ["ansible", "Ansible"],
  ["ansible", "Ansible"],
  ["helm", "Helm"],
  ["helm", "Helm"],
  ["microservices", "Microservices"],
  ["microservices", "Microservices"],
  ["api design", "API Design"],
  ["api design", "API Design"],
  ["system design", "System Design"],
  ["system design", "System Design"],
  ["distributed systems", "System Design"],
  ["devops", "DevOps"],
  ["devops", "DevOps"],
  ["dev ops", "DevOps"],
  ["sre", "SRE"],
  ["sre", "SRE"],
  ["site reliability engineering", "SRE"],
  ["security", "Security"],
  ["security", "Security"],
  ["cybersecurity", "Security"],
  ["penetration testing", "Penetration Testing"],
  ["pentest", "Penetration Testing"],
  ["penetration testing", "Penetration Testing"],
  ["oauth", "OAuth"],
  ["oauth", "OAuth"],
  ["oauth2", "OAuth"],
  ["jwt", "JWT"],
  ["jwt", "JWT"],
  ["blockchain", "Blockchain"],
  ["blockchain", "Blockchain"],
  ["web3", "Blockchain"],
  ["solidity", "Solidity"],
  ["solidity", "Solidity"],
  ["sap", "SAP"],
  ["sap", "SAP"],
  ["oracle", "Oracle"],
  ["oracle", "Oracle"],
  ["oracle db", "Oracle"],
  ["snowflake", "Snowflake"],
  ["snowflake", "Snowflake"],
  ["dbt", "dbt"],
  ["dbt", "dbt"],
  ["airflow", "Airflow"],
  ["airflow", "Airflow"],
  ["apache airflow", "Airflow"],
  ["looker", "Looker"],
  ["looker", "Looker"],
  ["seo", "SEO"],
  ["seo", "SEO"],
  ["sem", "SEM"],
  ["sem", "SEM"],
  ["google ads", "SEM"],
  ["marketo", "Marketo"],
  ["marketo", "Marketo"],
  ["hubspot", "HubSpot"],
  ["hubspot", "HubSpot"],
  ["public speaking", "Public Speaking"],
  ["public speaking", "Public Speaking"],
  ["technical writing", "Technical Writing"],
  ["technical writing", "Technical Writing"],
  ["customer success", "Customer Success"],
  ["customer success", "Customer Success"],
  ["recruiting", "Recruiting"],
  ["recruiting", "Recruiting"],
  ["talent acquisition", "Recruiting"],
  ["supply chain", "Supply Chain"],
  ["supply chain", "Supply Chain"],
  ["logistics", "Supply Chain"],
  ["six sigma", "Six Sigma"],
  ["six sigma", "Six Sigma"],
  ["lean six sigma", "Six Sigma"],
  ["quality assurance", "Quality Assurance"],
  ["qa", "Quality Assurance"],
  ["quality assurance", "Quality Assurance"],
  ["selenium", "Selenium"],
  ["selenium", "Selenium"],
  ["cypress", "Cypress"],
  ["cypress", "Cypress"],
  ["jest", "Jest"],
  ["jest", "Jest"],
  ["playwright", "Playwright"],
  ["playwright", "Playwright"],
  ["unit testing", "Unit Testing"],
  ["unit testing", "Unit Testing"],
  ["unit tests", "Unit Testing"],
  ["tdd", "TDD"],
  ["tdd", "TDD"],
  ["bdd", "BDD"],
  ["bdd", "BDD"],
  ["matlab", "MATLAB"],
  ["matlab", "MATLAB"],
  ["stata", "Stata"],
  ["stata", "Stata"],
  ["sas", "SAS"],
  ["sas", "SAS"],
  ["spss", "SPSS"],
  ["spss", "SPSS"],
  ["nursing", "Nursing"],
  ["nursing", "Nursing"],
  ["rn", "Nursing"],
  ["pharmacology", "Pharmacology"],
  ["pharmacology", "Pharmacology"],
  ["medical coding", "Medical Coding"],
  ["medical coding", "Medical Coding"],
  ["icd-10", "Medical Coding"],
  ["telehealth", "Telehealth"],
  ["telehealth", "Telehealth"],
  ["telemedicine", "Telehealth"],
  ["real estate", "Real Estate"],
  ["real estate", "Real Estate"],
  ["mortgage", "Mortgage"],
  ["mortgage", "Mortgage"],
  ["underwriting", "Underwriting"],
  ["underwriting", "Underwriting"],
  ["actuarial", "Actuarial"],
  ["actuarial", "Actuarial"],
  ["copywriting", "Copywriting"],
  ["copywriting", "Copywriting"],
  ["video editing", "Video Editing"],
  ["video editing", "Video Editing"],
  ["premiere pro", "Video Editing"],
  ["brand strategy", "Brand Strategy"],
  ["brand strategy", "Brand Strategy"],
  ["paralegal", "Paralegal"],
  ["paralegal", "Paralegal"],
  ["intellectual property", "Intellectual Property"],
  ["intellectual property", "Intellectual Property"],
  ["ip law", "Intellectual Property"],
  ["mergers and acquisitions", "Mergers and Acquisitions"],
  ["m&a", "Mergers and Acquisitions"],
  ["mergers and acquisitions", "Mergers and Acquisitions"],
  ["artificial intelligence", "Artificial Intelligence"],
  ["ai", "Artificial Intelligence"],
  ["artificial intelligence", "Artificial Intelligence"],
  ["llm", "LLM"],
  ["llm", "LLM"],
  ["large language model", "LLM"],
  ["gen ai", "LLM"],
  ["generative ai", "LLM"],
  ["openai", "OpenAI"],
  ["openai", "OpenAI"],
  ["chatgpt", "OpenAI"],
  ["gpt-4", "OpenAI"],
  ["langchain", "LangChain"],
  ["langchain", "LangChain"],
  ["lang chain", "LangChain"],
  ["huggingface", "HuggingFace"],
  ["huggingface", "HuggingFace"],
  ["hugging face", "HuggingFace"],
  ["transformers hf", "HuggingFace"],
  ["pandas", "Pandas"],
  ["pandas", "Pandas"],
  ["pd python", "Pandas"],
  ["numpy", "NumPy"],
  ["numpy", "NumPy"],
  ["np python", "NumPy"],
  ["scipy", "SciPy"],
  ["scipy", "SciPy"],
  ["scikit-learn", "Scikit-learn"],
  ["scikit-learn", "Scikit-learn"],
  ["sklearn", "Scikit-learn"],
  ["scikit learn", "Scikit-learn"],
  ["keras", "Keras"],
  ["keras", "Keras"],
  ["xgboost", "XGBoost"],
  ["xgboost", "XGBoost"],
  ["lightgbm", "LightGBM"],
  ["lightgbm", "LightGBM"],
  ["catboost", "CatBoost"],
  ["catboost", "CatBoost"],
  ["feature engineering", "Feature Engineering"],
  ["feature engineering", "Feature Engineering"],
  ["mlops", "MLOps"],
  ["mlops", "MLOps"],
  ["ml ops", "MLOps"],
  ["kubeflow", "Kubeflow"],
  ["kubeflow", "Kubeflow"],
  ["mlflow", "MLflow"],
  ["mlflow", "MLflow"],
  ["data warehousing", "Data Warehousing"],
  ["data warehousing", "Data Warehousing"],
  ["data warehouse", "Data Warehousing"],
  ["business intelligence", "Business Intelligence"],
  ["business intelligence", "Business Intelligence"],
  ["bi", "Business Intelligence"],
  ["etl", "ETL"],
  ["etl", "ETL"],
  ["extract transform load", "ETL"],
  ["informatica", "Informatica"],
  ["informatica", "Informatica"],
  ["talend", "Talend"],
  ["talend", "Talend"],
  ["cloudformation", "CloudFormation"],
  ["cloudformation", "CloudFormation"],
  ["cfn", "CloudFormation"],
  ["azure devops", "Azure DevOps"],
  ["azure devops", "Azure DevOps"],
  ["ado", "Azure DevOps"],
  ["google bigquery", "Google BigQuery"],
  ["bigquery", "Google BigQuery"],
  ["google bigquery", "Google BigQuery"],
  ["redshift", "Redshift"],
  ["redshift", "Redshift"],
  ["aws redshift", "Redshift"],
  ["dynamodb", "DynamoDB"],
  ["dynamodb", "DynamoDB"],
  ["cosmosdb", "CosmosDB"],
  ["cosmosdb", "CosmosDB"],
  ["cosmos db", "CosmosDB"],
  ["firebase", "Firebase"],
  ["firebase", "Firebase"],
  ["supabase", "Supabase"],
  ["supabase", "Supabase"],
  ["prisma", "Prisma"],
  ["prisma", "Prisma"],
  ["prisma orm", "Prisma"],
  ["grpc", "gRPC"],
  ["grpc", "gRPC"],
  ["websocket", "WebSocket"],
  ["websocket", "WebSocket"],
  ["websockets", "WebSocket"],
  ["rabbitmq", "RabbitMQ"],
  ["rabbitmq", "RabbitMQ"],
  ["activemq", "ActiveMQ"],
  ["activemq", "ActiveMQ"],
  ["nginx", "Nginx"],
  ["nginx", "Nginx"],
  ["apache", "Apache"],
  ["apache", "Apache"],
  ["apache http", "Apache"],
  ["tomcat", "Tomcat"],
  ["tomcat", "Tomcat"],
  ["iis", "IIS"],
  ["iis", "IIS"],
  ["loadbalancer", "LoadBalancer"],
  ["load balancer", "LoadBalancer"],
  ["load balancing", "LoadBalancer"],
  ["cdn", "CDN"],
  ["cdn", "CDN"],
  ["content delivery network", "CDN"],
  ["cloudflare", "Cloudflare"],
  ["cloudflare", "Cloudflare"],
  ["networking", "Networking"],
  ["networking", "Networking"],
  ["tcp/ip", "Networking"],
  ["dns", "Networking"],
  ["vpn", "VPN"],
  ["vpn", "VPN"],
  ["firewall", "Firewall"],
  ["firewall", "Firewall"],
  ["waf", "Firewall"],
  ["iam", "IAM"],
  ["iam", "IAM"],
  ["identity access management", "IAM"],
  ["soc2", "SOC2"],
  ["soc2", "SOC2"],
  ["soc 2", "SOC2"],
  ["gdpr", "GDPR"],
  ["gdpr", "GDPR"],
  ["pci", "PCI"],
  ["pci", "PCI"],
  ["pci dss", "PCI"],
  ["itil", "ITIL"],
  ["itil", "ITIL"],
  ["cobit", "COBIT"],
  ["cobit", "COBIT"],
  ["togaf", "TOGAF"],
  ["togaf", "TOGAF"],
  ["enterprise architecture", "TOGAF"],
  ["bpmn", "BPMN"],
  ["bpmn", "BPMN"],
  ["process modeling", "BPMN"],
  ["uml", "UML"],
  ["uml", "UML"],
  ["wireframing", "Wireframing"],
  ["wireframing", "Wireframing"],
  ["wireframes", "Wireframing"],
  ["prototyping", "Prototyping"],
  ["prototyping", "Prototyping"],
  ["prototypes", "Prototyping"],
  ["accessibility", "Accessibility"],
  ["accessibility", "Accessibility"],
  ["a11y", "Accessibility"],
  ["wcag", "Accessibility"],
  ["responsivedesign", "ResponsiveDesign"],
  ["responsive design", "ResponsiveDesign"],
  ["mobile first", "ResponsiveDesign"],
  ["typeorm", "TypeORM"],
  ["typeorm", "TypeORM"],
  ["sequelize", "Sequelize"],
  ["sequelize", "Sequelize"],
  ["hibernate", "Hibernate"],
  ["hibernate", "Hibernate"],
  ["jpa", "JPA"],
  ["jpa", "JPA"],
  ["mockito", "Mockito"],
  ["mockito", "Mockito"],
  ["junit", "JUnit"],
  ["junit", "JUnit"],
  ["pytest", "PyTest"],
  ["pytest", "PyTest"],
  ["rspec", "RSpec"],
  ["rspec", "RSpec"],
  ["mocha", "Mocha"],
  ["mocha", "Mocha"],
  ["chai", "Chai"],
  ["chai", "Chai"],
  ["eslint", "ESLint"],
  ["eslint", "ESLint"],
  ["prettier", "Prettier"],
  ["prettier", "Prettier"],
  ["webpack", "Webpack"],
  ["webpack", "Webpack"],
  ["vite", "Vite"],
  ["vite", "Vite"],
  ["rollup", "Rollup"],
  ["rollup", "Rollup"],
  ["babel", "Babel"],
  ["babel", "Babel"],
  ["storybook", "Storybook"],
  ["storybook", "Storybook"],
  ["redux", "Redux"],
  ["redux", "Redux"],
  ["zustand", "Zustand"],
  ["zustand", "Zustand"],
  ["mobx", "MobX"],
  ["mobx", "MobX"],
  ["rxjs", "RxJS"],
  ["rxjs", "RxJS"],
  ["threejs", "ThreeJS"],
  ["three.js", "ThreeJS"],
  ["threejs", "ThreeJS"],
  ["d3", "D3"],
  ["d3", "D3"],
  ["d3.js", "D3"],
  ["canvas", "Canvas"],
  ["canvas api", "Canvas"],
  ["webgl", "WebGL"],
  ["webgl", "WebGL"],
  ["unity", "Unity"],
  ["unity", "Unity"],
  ["unity3d", "Unity"],
  ["unreal", "Unreal"],
  ["unreal", "Unreal"],
  ["unreal engine", "Unreal"],
  ["gamedev", "GameDev"],
  ["game development", "GameDev"],
  ["gamedev", "GameDev"],
  ["ar", "AR"],
  ["augmented reality", "AR"],
  ["ar", "AR"],
  ["vr", "VR"],
  ["virtual reality", "VR"],
  ["vr", "VR"],
  ["iot", "IoT"],
  ["iot", "IoT"],
  ["internet of things", "IoT"],
  ["embedded", "Embedded"],
  ["embedded systems", "Embedded"],
  ["embedded c", "Embedded"],
  ["fpga", "FPGA"],
  ["fpga", "FPGA"],
  ["verilog", "Verilog"],
  ["verilog", "Verilog"],
  ["vhdl", "VHDL"],
  ["vhdl", "VHDL"],
  ["simulink", "Simulink"],
  ["simulink", "Simulink"],
  ["autocad", "AutoCAD"],
  ["autocad", "AutoCAD"],
  ["solidworks", "SolidWorks"],
  ["solidworks", "SolidWorks"],
  ["revit", "Revit"],
  ["revit", "Revit"],
  ["bim", "Revit"],
  ["lean", "Lean"],
  ["lean manufacturing", "Lean"],
  ["lean", "Lean"],
  ["kaizen", "Kaizen"],
  ["kaizen", "Kaizen"],
  ["kanban", "Kanban"],
  ["kanban board", "Kanban"],
  ["okr", "OKR"],
  ["okr", "OKR"],
  ["objectives key results", "OKR"],
  ["kpi", "KPI"],
  ["kpi", "KPI"],
  ["key performance indicators", "KPI"],
  ["forecasting", "Forecasting"],
  ["forecasting", "Forecasting"],
  ["demand forecasting", "Forecasting"],
  ["budgeting", "Budgeting"],
  ["budgeting", "Budgeting"],
  ["budget management", "Budgeting"],
  ["auditing", "Auditing"],
  ["auditing", "Auditing"],
  ["internal audit", "Auditing"],
  ["tax", "Tax"],
  ["tax", "Tax"],
  ["tax preparation", "Tax"],
  ["payroll", "Payroll"],
  ["payroll processing", "Payroll"],
  ["quickbooks", "QuickBooks"],
  ["quickbooks", "QuickBooks"],
  ["netsuite", "NetSuite"],
  ["netsuite", "NetSuite"],
  ["workday", "Workday"],
  ["workday", "Workday"],
  ["servicenow", "ServiceNow"],
  ["servicenow", "ServiceNow"],
  ["zendesk", "Zendesk"],
  ["zendesk", "Zendesk"],
  ["intercom", "Intercom"],
  ["intercom", "Intercom"],
  ["slack", "Slack"],
  ["slack", "Slack"],
  ["teams", "Teams"],
  ["microsoft teams", "Teams"],
  ["ms teams", "Teams"],
  ["zoom", "Zoom"],
  ["zoom", "Zoom"],
  ["notion", "Notion"],
  ["notion", "Notion"],
  ["asana", "Asana"],
  ["asana", "Asana"],
  ["trello", "Trello"],
  ["trello", "Trello"],
  ["monday", "Monday"],
  ["monday.com", "Monday"],
  ["monday", "Monday"],
  ["airtable", "Airtable"],
  ["airtable", "Airtable"],
  ["outreach", "Outreach"],
  ["outreach sales", "Outreach"],
  ["gong", "Gong"],
  ["gong.io", "Gong"],
  ["gong", "Gong"],
  ["clari", "Clari"],
  ["clari", "Clari"],
  ["cpq", "CPQ"],
  ["cpq", "CPQ"],
  ["configure price quote", "CPQ"],
  ["revops", "RevOps"],
  ["revops", "RevOps"],
  ["revenue operations", "RevOps"],
  ["enablement", "Enablement"],
  ["sales enablement", "Enablement"],
  ["coldcalling", "ColdCalling"],
  ["cold calling", "ColdCalling"],
  ["demoskills", "DemoSkills"],
  ["product demo", "DemoSkills"],
  ["demos", "DemoSkills"],
  ["churn", "Churn"],
  ["churn reduction", "Churn"],
  ["retention", "Churn"],
  ["nps", "NPS"],
  ["nps", "NPS"],
  ["net promoter score", "NPS"],
  ["csat", "CSAT"],
  ["csat", "CSAT"],
  ["phlebotomy", "Phlebotomy"],
  ["phlebotomy", "Phlebotomy"],
  ["radiology", "Radiology"],
  ["radiology", "Radiology"],
  ["surgery", "Surgery"],
  ["surgery", "Surgery"],
  ["surgical", "Surgery"],
  ["pediatrics", "Pediatrics"],
  ["pediatrics", "Pediatrics"],
  ["oncology", "Oncology"],
  ["oncology", "Oncology"],
  ["cardiology", "Cardiology"],
  ["cardiology", "Cardiology"],
  ["dentistry", "Dentistry"],
  ["dentistry", "Dentistry"],
  ["dental", "Dentistry"],
  ["physicaltherapy", "PhysicalTherapy"],
  ["physical therapy", "PhysicalTherapy"],
  ["pt therapy", "PhysicalTherapy"],
  ["occupationaltherapy", "OccupationalTherapy"],
  ["occupational therapy", "OccupationalTherapy"],
  ["ot therapy", "OccupationalTherapy"],
  ["socialwork", "SocialWork"],
  ["social work", "SocialWork"],
  ["psychology", "Psychology"],
  ["psychology", "Psychology"],
  ["clinical psychology", "Psychology"],
  ["counseling", "Counseling"],
  ["counseling", "Counseling"],
  ["curriculum", "Curriculum"],
  ["curriculum development", "Curriculum"],
  ["instructionaldesign", "InstructionalDesign"],
  ["instructional design", "InstructionalDesign"],
  ["ld", "InstructionalDesign"],
  ["lms", "LMS"],
  ["lms", "LMS"],
  ["learning management system", "LMS"],
  ["moodle", "Moodle"],
  ["moodle", "Moodle"],
  ["canvaslms", "CanvasLMS"],
  ["canvas lms", "CanvasLMS"],
  ["translation", "Translation"],
  ["translation", "Translation"],
  ["localization", "Translation"],
  ["interpretation", "Interpretation"],
  ["interpretation", "Interpretation"],
  ["journalism", "Journalism"],
  ["journalism", "Journalism"],
  ["editing", "Editing"],
  ["editing", "Editing"],
  ["proofreading", "Editing"],
  ["apstyle", "APStyle"],
  ["ap style", "APStyle"],
  ["mediarelations", "MediaRelations"],
  ["media relations", "MediaRelations"],
  ["pr", "MediaRelations"],
  ["eventplanning", "EventPlanning"],
  ["event planning", "EventPlanning"],
  ["events", "EventPlanning"],
  ["hospitality", "Hospitality"],
  ["hospitality", "Hospitality"],
  ["culinary", "Culinary"],
  ["culinary", "Culinary"],
  ["chef", "Culinary"],
  ["foodsafety", "FoodSafety"],
  ["food safety", "FoodSafety"],
  ["servsafe", "FoodSafety"],
  ["osha", "OSHA"],
  ["osha", "OSHA"],
  ["workplace safety", "OSHA"],
  ["warehouse", "Warehouse"],
  ["warehouse operations", "Warehouse"],
  ["wms", "Warehouse"],
  ["forklift", "Forklift"],
  ["forklift operator", "Forklift"],
  ["cdl", "CDL"],
  ["cdl", "CDL"],
  ["commercial driver", "CDL"],
  ["hvac", "HVAC"],
  ["hvac", "HVAC"],
  ["electrician", "Electrician"],
  ["electrician", "Electrician"],
  ["plumbing", "Plumbing"],
  ["plumbing", "Plumbing"],
  ["carpentry", "Carpentry"],
  ["carpentry", "Carpentry"],
  ["welding", "Welding"],
  ["welding", "Welding"],
  ["cnc", "CNC"],
  ["cnc", "CNC"],
  ["cnc machining", "CNC"],
  ["qualitycontrol", "QualityControl"],
  ["quality control", "QualityControl"],
  ["qc", "QualityControl"],
  ["iso9001", "ISO9001"],
  ["iso 9001", "ISO9001"],
  ["iso9001", "ISO9001"],
  ["fda", "FDA"],
  ["fda regulations", "FDA"],
  ["gmp", "GMP"],
  ["gmp", "GMP"],
  ["good manufacturing practice", "GMP"],
  ["clinicaltrials", "ClinicalTrials"],
  ["clinical trial management", "ClinicalTrials"],
  ["pharmacovigilance", "Pharmacovigilance"],
  ["pharmacovigilance", "Pharmacovigilance"],
  ["biostatistics", "Biostatistics"],
  ["biostatistics", "Biostatistics"],
  ["genomics", "Genomics"],
  ["genomics", "Genomics"],
  ["bioinformatics", "Bioinformatics"],
  ["bioinformatics", "Bioinformatics"],
  ["labtechniques", "LabTechniques"],
  ["lab techniques", "LabTechniques"],
  ["laboratory", "LabTechniques"],
  ["pcr", "PCR"],
  ["pcr", "PCR"],
  ["crispr", "CRISPR"],
  ["crispr", "CRISPR"],
  ["immunology", "Immunology"],
  ["immunology", "Immunology"],
  ["pathology", "Pathology"],
  ["pathology", "Pathology"],
  ["anesthesia", "Anesthesia"],
  ["anesthesia", "Anesthesia"],
  ["emr", "EMR"],
  ["emr systems", "EMR"],
  ["epic", "Epic"],
  ["epic ehr", "Epic"],
  ["epic systems", "Epic"],
  ["cerner", "Cerner"],
  ["cerner", "Cerner"],
  ["meditech", "Meditech"],
  ["meditech", "Meditech"],
  ["arbitration", "Arbitration"],
  ["arbitration", "Arbitration"],
  ["mediation", "Mediation"],
  ["mediation", "Mediation"],
  ["corporatelaw", "CorporateLaw"],
  ["corporate law", "CorporateLaw"],
  ["taxlaw", "TaxLaw"],
  ["tax law", "TaxLaw"],
  ["employmentlaw", "EmploymentLaw"],
  ["employment law", "EmploymentLaw"],
  ["labor law", "EmploymentLaw"],
  ["realestatelaw", "RealEstateLaw"],
  ["real estate law", "RealEstateLaw"],
  ["duediligence", "DueDiligence"],
  ["due diligence", "DueDiligence"],
  ["discovery", "Discovery"],
  ["e-discovery", "Discovery"],
  ["ediscovery", "Discovery"],
  ["briefwriting", "BriefWriting"],
  ["brief writing", "BriefWriting"],
  ["legal briefs", "BriefWriting"],
  ["notary", "Notary"],
  ["notary", "Notary"],
  ["complianceofficer", "ComplianceOfficer"],
  ["compliance officer", "ComplianceOfficer"],
  ["cco", "ComplianceOfficer"],
  ["aml", "AML"],
  ["aml", "AML"],
  ["anti money laundering", "AML"],
  ["kyc", "KYC"],
  ["kyc", "KYC"],
  ["know your customer", "KYC"],
  ["sox", "SOX"],
  ["sox", "SOX"],
  ["sarbanes oxley", "SOX"],
  ["ifrs", "IFRS"],
  ["ifrs", "IFRS"],
  ["gaap", "GAAP"],
  ["gaap accounting", "GAAP"],
  ["cfa", "CFA"],
  ["cfa", "CFA"],
  ["cpa", "CPA"],
  ["cpa", "CPA"],
  ["cfp", "CFP"],
  ["cfp", "CFP"],
  ["series7", "Series7"],
  ["series 7", "Series7"],
  ["series63", "Series63"],
  ["series 63", "Series63"],
  ["fixedincome", "FixedIncome"],
  ["fixed income", "FixedIncome"],
  ["bonds", "FixedIncome"],
  ["equities", "Equities"],
  ["equities", "Equities"],
  ["equity research", "Equities"],
  ["derivatives", "Derivatives"],
  ["derivatives", "Derivatives"],
  ["options trading", "Derivatives"],
  ["portfoliomanagement", "PortfolioManagement"],
  ["portfolio management", "PortfolioManagement"],
  ["wealthmanagement", "WealthManagement"],
  ["wealth management", "WealthManagement"],
  ["privateequity", "PrivateEquity"],
  ["private equity", "PrivateEquity"],
  ["pe", "PrivateEquity"],
  ["venturecapital", "VentureCapital"],
  ["venture capital", "VentureCapital"],
  ["vc", "VentureCapital"],
  ["investmentbanking", "InvestmentBanking"],
  ["investment banking", "InvestmentBanking"],
  ["ib", "InvestmentBanking"],
  ["mergersmodeling", "MergersModeling"],
  ["merger models", "MergersModeling"],
  ["lbo modeling", "MergersModeling"],
  ["valuation", "Valuation"],
  ["valuation", "Valuation"],
  ["dcf valuation", "Valuation"],
  ["pitchdecks", "PitchDecks"],
  ["pitch decks", "PitchDecks"],
  ["investor decks", "PitchDecks"],
];
