import { z } from "zod";

export const CandidateProfileSchema = z.object({
  name: z.string().min(2).optional(),
  headline: z.string().optional(),
  phone: z.string().optional(),
  location: z.string().optional(),
  summary: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  school: z.string().optional(),
  graduationYear: z.string().optional(),
  linkedInUrl: z.string().optional(),
  githubUrl: z.string().optional(),
  websiteUrl: z.string().optional(),
  jobAlerts: z.boolean().optional(),
  aiSuggestions: z.boolean().optional(),
  publicProfile: z.boolean().optional(),
  preferredRoles: z.array(z.string()).optional(),
  salaryExpectationMin: z.number().int().optional(),
  salaryExpectationMax: z.number().int().optional(),
  visibility: z.enum(["PUBLIC", "PRIVATE", "RECRUITERS_ONLY"]).optional(),
  educations: z.array(z.object({
    id: z.string().optional(),
    school: z.string(),
    degree: z.string(),
    field: z.string(),
    startYear: z.string(),
    endYear: z.string(),
  })).optional(),
  skillRecords: z.array(z.object({
    id: z.string().optional(),
    name: z.string(),
    level: z.string().optional(),
  })).optional(),
});
